import assert from 'node:assert/strict';
import {normalizeEntry,exampleEntries,buildCards,validateBackup,aggregate} from '../dist/core.js';
const samples=exampleEntries();
assert.equal(samples.length,4);
assert.deepEqual(aggregate(samples,[]),{shifts:3,drinks:3,total:23,attempts:0,gotIt:0,again:0});
const deck=buildCards(samples,[]);assert.equal(deck.length,12);
assert.equal(new Set(deck.map(x=>x.id)).size,12);
assert.equal(deck.filter(x=>x.drink==='Cappuccino').length,4);
assert.ok(deck.find(x=>x.drink==='Cappuccino'&&x.id.endsWith(':steps')).answer.includes('wand position'));
assert.ok(!deck.find(x=>x.drink==='Cappuccino'&&x.id.endsWith(':steps')).answer.includes('café’s routine'));
const nullShot=normalizeEntry({...samples[0],id:'no-shots',shots:'',steps:'1. First\n2. Second'});assert.equal(nullShot.shots,null);assert.deepEqual(nullShot.steps,['First','Second']);
assert.equal(buildCards([nullShot],[]).filter(x=>x.id.endsWith(':shots')).length,0);
assert.throws(()=>normalizeEntry({...samples[0],date:'2026-02-30'}));
assert.throws(()=>normalizeEntry({...samples[0],count:0}));
assert.throws(()=>normalizeEntry({...samples[0],confidence:6}));
assert.throws(()=>validateBackup({version:1,entries:[samples[0],samples[0]],attempts:[]}));
assert.throws(()=>validateBackup({version:1,entries:samples,attempts:[{id:'a',entryId:'unknown',rating:'got-it'}]}));
assert.deepEqual(validateBackup({version:1,entries:samples,attempts:[]}).entries,samples);
const attempts=[{id:'a',entryId:'demo-americano-1',cardId:'demo-americano-1:shots',rating:'again',date:new Date().toISOString()}];assert.equal(buildCards(samples,attempts)[0].id,'demo-americano-1:shots');
assert.equal(buildCards(samples,[],'phrases').length,3);
assert.equal(buildCards(samples,[],'recall','Latte').length,4);
console.log('PASS: recipe validation, backup integrity, latest recipe cards, prioritized review, phrase cards, and progress aggregation.');
